"""question_model

Revision ID: 9d26d4593f47
Revises: c9266e53ab77
Create Date: 2023-02-27 23:41:35.549153

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9d26d4593f47"
down_revision = "c9266e53ab77"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    questions_table = op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("answer", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.bulk_insert(
        questions_table,
        [
            {"title": f"What is {i} + {j} ?", "answer": f"{i + j}"}
            for i in range(10)
            for j in range(10)
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("questions")
    # ### end Alembic commands ###
