"""add_statistic

Revision ID: b0ae07c3e506
Revises: bfe95f8e98fc
Create Date: 2023-03-07 21:20:00.895801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ae07c3e506'
down_revision = 'bfe95f8e98fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('loses', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('canceled', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('ans_correct', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('ans_wrong', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('ans_late', sa.Integer(), nullable=True))

    op.execute("UPDATE games SET wins = 0")
    op.execute("UPDATE games SET loses = 0")
    op.execute("UPDATE games SET canceled = 0")
    op.execute("UPDATE players SET ans_correct = 0")
    op.execute("UPDATE players SET ans_wrong = 0")
    op.execute("UPDATE players SET ans_late = 0")

    op.alter_column("games", "wins", nullable=False)
    op.alter_column("games", "loses", nullable=False)
    op.alter_column("games", "canceled", nullable=False)
    op.alter_column("players", "ans_correct", nullable=False)
    op.alter_column("players", "ans_wrong", nullable=False)
    op.alter_column("players", "ans_late", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'ans_late')
    op.drop_column('players', 'ans_wrong')
    op.drop_column('players', 'ans_correct')
    op.drop_column('games', 'canceled')
    op.drop_column('games', 'loses')
    op.drop_column('games', 'wins')
    # ### end Alembic commands ###
