"""models

Revision ID: bfe95f8e98fc
Revises: 
Create Date: 2023-03-05 01:28:15.014941

"""
from hashlib import sha256

from alembic import op
import sqlalchemy as sa
from ruamel import yaml


# revision identifiers, used by Alembic.
revision = 'bfe95f8e98fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    admins_table = op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score_host', sa.Integer(), nullable=False),
    sa.Column('score_team', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('q_history', sa.String(), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.Column('responder_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    questions_table = op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with open("./env/dev.env.yaml", "r") as f:
        raw_config = yaml.safe_load(f)
    op.bulk_insert(
        admins_table,
        [
            {
                "email": raw_config["admin"]["email"],
                "password": sha256(
                    raw_config["admin"]["password"].encode()
                ).hexdigest(),
            },
        ],
    )
    op.bulk_insert(
        questions_table,
        [
            {"title": f"What is {i} + {j} ?", "answer": f"{i + j}"}
            for i in range(10)
            for j in range(10)
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('players')
    op.drop_table('games')
    op.drop_table('admins')
    # ### end Alembic commands ###
