"""add_admin_table

Revision ID: c9266e53ab77
Revises: 
Create Date: 2023-02-26 22:28:08.249647

"""
from hashlib import sha256

from alembic import op
import sqlalchemy as sa
from ruamel import yaml

# revision identifiers, used by Alembic.
revision = "c9266e53ab77"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    admins_table = op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with open("./env/dev.env.yaml", "r") as f:
        raw_config = yaml.safe_load(f)
    op.bulk_insert(
        admins_table,
        [
            {
                "email": raw_config["admin"]["email"],
                "password": sha256(
                    raw_config["admin"]["password"].encode()
                ).hexdigest(),
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admins")
    # ### end Alembic commands ###
